[build]
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/stream"
  to = "/.netlify/functions/stream"
  status = 200

[[redirects]]
  from = "/subtitle"
  to = "/.netlify/functions/subtitle"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
